# Factorización $LU$

Esta factorización consiste en determinar una forma equivalente para la matriz $A$ en la forma:


$$A = LU$$


Donde, $L$ es una matriz triangular inferior y $U$ es una matriz triangular superior, ahora bien, es importante señalar que no toda matriz no singular puede ser factorizada de esta forma, pero si una gran mayoría, por otra parte esta factorización nos beneficia al reducir el tiempo empleada en la solución del sistema.

In [17]:
# Importamos la libreria de numpy para manipular arreglos y álgebra lineal
from numpy import array, zeros
import numpy as np

# Importamos la función señalada del determinante
from numpy.linalg import det, solve, inv

# Importamos la función para el método lu
from scipy.linalg import lu

In [9]:
# Definimos la matriz con la que estaremos trabajando
A = array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]], dtype = float)
B = array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]], dtype = float)

In [10]:
# Validamos que la matriz es invertible

# Calculamos el tamaño del sistema
n = len(A)

if (det(A[:,:n]) != 0 and abs(det(A[:,:n])) > 10 ** (-5)):

    # Construimos una matriz aumentada
    matrizA = np.zeros((n,2 * n))
    
    # Asignamos los elementos de la matriz aumentada para determinar la factorización LU
    matrizA[:,0:n] = A.copy()
    matrizA[:,n:] = np.eye(n)
    
    print('La matriz aumentada con la que trabajaremos es: \n', matrizA, '\n')

    # Ahora identificamos como se debe proceder para reducir la matriz para la siguiente fila

    # Tomamos la fila para pivote de eliminación hacía abajo
    for j in range(n):
        
        # Procedemos a validar si el coeficiente de la línea pivote no es cero
        pivote = matrizA[j,j]
        
        # Verificamos si el pivote es diferente de cero
        if pivote == 0:
            
            # Buscamos aquella celda pivote que sea diferente de cero
            for k in range(j+1, n):
                
                # Determinamos la que es diferente de k
                if matrizA[k,j] != 0 :
                    
                    # Auxiliar
                    cambio = matrizA[j,:].copy()
                    
                    # Cambiamos lineas
                    matrizA[j,:] = matrizA[k,:].copy()
                    matrizA[k,:] = cambio.copy()
                    
                    # Rompemos el ciclo for
                    break
        
        # Eliminamos las bajo la fila pivote
        for i in range(j+1, n):
            
            # Determinamos el coeficiente a aplicar en cada fila
            coef = matrizA[i,j] / matrizA[j,j]

            # Realizamos la eliminación
            matrizA[i,:] = matrizA[i,:] - coef * matrizA[j,:]
    
    # Imprimimos la matriz triangular inferior del proceso de eliminación
    print('La matriz L es: \n', matrizA[:,n:], '\n')
    
    # Imprimimos la matriz triangular superior
    print('La matriz U es: \n', matrizA[:,0:n], '\n')
    
else:
    
    print('La matriz no tiene solución única')

La matriz aumentada con la que trabajaremos es: 
 [[ 1.  1.  0.  3.  1.  0.  0.  0.]
 [ 2.  1. -1.  1.  0.  1.  0.  0.]
 [ 3. -1. -1.  2.  0.  0.  1.  0.]
 [-1.  2.  3. -1.  0.  0.  0.  1.]] 

La matriz L es: 
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 5. -4.  1.  0.]
 [-5.  3.  0.  1.]] 

La matriz U es: 
 [[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]] 



In [14]:
# Validemos el producto y que este da como resultado
inv(matrizA[:,n:]) @ matrizA[:,0:n]

array([[ 1.00000000e+00,  1.00000000e+00,  1.77635684e-16,
         3.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00, -1.00000000e+00,
         1.00000000e+00],
       [ 3.00000000e+00, -1.00000000e+00, -1.00000000e+00,
         2.00000000e+00],
       [-1.00000000e+00,  2.00000000e+00,  3.00000000e+00,
        -1.00000000e+00]])