# Matriz Inversa


Se dice que una matriz $A$ de tamaño $n\times n$ es **no singular** o **invertible**, si existe una matriz $A^{-1}$ de $n\times n$ con $AA^{-1} = A^{-1}A = I$, con $I$ la matriz identidad. A la matriz $A^{-1}$ se le llama la inversa de la matriz $A$. Una matriz que no tiene inversa recibe el nombre de **singular** o no **invertible**.


hora bien, como podemos determinar la inversa en el caso general de que no tengamos la solución del sistema, para realizar este proceso, lo más común es realizar la eliminación de la matriz $A$ y convertirla en la identidad con la matriz aumentada de la identidad, es decir:


\begin{equation*}
    \left[A | I\right]\;\;\Rightarrow\;\;\left[I | A^{-1}\right],
\end{equation*}


lo anterior siempre y cuando la matriz sea no singular, sino no podremos obtener en ningún momento la matriz identidad. Para lo anterior, lo más conveniente es obtener una variante del método de eliminación gaussiana a fin de obtener el método de Gauss - Jordan (el cual permite obtener la matriz identidad).

In [4]:
# Importamos la libreria de numpy para manipular arreglos y álgebra lineal
from numpy import array, zeros
import numpy as np

# Importamos la función señalada del determinante
from numpy.linalg import det, solve, inv

In [2]:
# Definimos la matriz con la que estaremos trabajando
A = array([[2, 0, 1, 2], [1, 1, 0, 2], [2, -1, 3, 1], [3, -1, 4, 3]], dtype = float)

In [3]:
# Calculamos la longitud de la matriz a invertir
n = len(A)

# Creamos una matriz aumentada con la identidad
matrizA = np.zeros((n,2 * n))

# Asiganamos las matrices correspondientes
matrizA[:,0:n] = A.copy()
matrizA[:,n:] = np.eye(n)

# Validamos que la matriz es invertible
if (det(A) != 0 and det(A) > 10 ** (-5)):
    
    # Señalamos que se ha procedido a señalar que se sigue el método para la inversa
    print('Procedemos a determinar la matriz inversa por medio del método de Gauss - Jordan')

    # Ahora identificamos como se debe proceder para reducir la matriz para la siguiente fila

    # Tomamos la fila para pivote de eliminación hacía abajo
    for j in range(n):
        
        # Procedemos a validar si el coeficiente de la línea pivote no es cero
        pivote = matrizA[j,j]
        
        # Verificamos si el pivote es diferente de cero
        if pivote == 0:
            
            # Buscamos aquella celda pivote que sea diferente de cero
            for k in range(j+1, n):
                
                # Determinamos la que es diferente de k
                if matrizA[k,k] != 0 :
                    
                    # Auxiliar
                    cambio = matrizA[j,:].copy()
                    
                    # Cambiamos lineas
                    matrizA[j,:] = matrizA[k,:].copy()
                    matrizA[k,:] = cambio.copy()
                    
                    # Rompemos el ciclo for
                    break
        
        # Eliminamos las bajo la fila pivote
        for i in range(0,n):
            
            # Eliminamos completamente
            if i != j:
            
                # Determinamos el coeficiente a aplicar en cada fila
                coef = matrizA[i,j] / matrizA[j,j]

                # Realizamos la eliminación a la segunda fila
                matrizA[i,:] = matrizA[i,:] - coef * matrizA[j,:]
                
        # Dividimos por el valor señalado a fin de simplificar
        matrizA[j,:] = matrizA[j,:] / matrizA[j,j]
                
    # Imprimimos la matriz resultado del sistema de ecuaciones
    print('La matriz inversa resultado del proceso es: \n', matrizA[:,n:])
    
else:
    
    print('La matriz no tiene solución única')

Procedemos a determinar la matriz inversa por medio del método de Gauss - Jordan
La matriz inversa resultado del proceso es: 
 [[ 1.00000000e+00 -5.55111512e-17  1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  1.66666667e+00  1.66666667e+00 -1.00000000e+00]
 [-1.00000000e+00  6.66666667e-01  6.66666667e-01  0.00000000e+00]
 [ 0.00000000e+00 -3.33333333e-01 -1.33333333e+00  1.00000000e+00]]


In [5]:
# Validamos el calculo con la funcion directa
print('La matriz resultado de la matriz inversa \n', inv(A))

La matriz resultado de la matriz inversa 
 [[ 1.00000000e+00 -1.48029737e-16  1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  1.66666667e+00  1.66666667e+00 -1.00000000e+00]
 [-1.00000000e+00  6.66666667e-01  6.66666667e-01  2.46519033e-32]
 [-2.22044605e-16 -3.33333333e-01 -1.33333333e+00  1.00000000e+00]]
