# Sistemas de ecuaciones lineales

Considere un sistema de ecuaciones lineales conformado por $n$ ecuaciones:

\begin{equation}
	\begin{split}
		a_{11}x_{1} + a_{12}x_{2} + a_{13}x_{3} + \cdots + a_{1n}x_{n} & = b_{1} \\
		a_{21}x_{1} + a_{22}x_{2} + a_{23}x_{3} + \cdots + a_{2n}x_{n} & = b_{2} \\
		a_{31}x_{1} + a_{32}x_{2} + a_{33}x_{3} + \cdots + a_{3n}x_{n} & = b_{3} \\
		\vdots \;\;\;\;\;\;\;\;\;\;\;\vdots\;\;\;\;\;\;\;\;\;\;\;\vdots\;\;\;\;\;\;\;\vdots\;\;\;\;\;\;\;\;\; \vdots\;\;\;\;\;\; & \;\;\;\;\;\vdots \\
		a_{n1}x_{1}+a_{n2}x_{2}+a_{n3}x_{3}+\cdot+a_{nn}x_{n} & = b_{n} \\
	\end{split}
\end{equation}


Donde $\forall i,j = 1,2,3,\dots,n,\;\;a_{ij}\in\mathbb{R};\;\;\;\forall i = 1,2,3,\dots,n,\;\;b_{i}\in\mathbb{R}$, es decir, los coeficientes del sistema son números reales.


Para resolverlo procederemos a conformar la forma matricial


\begin{equation*}
	\left[ \begin{array}{ccccc|c}
	a_{11} &  a_{12} & a_{13} & \cdots & a_{1n} & b_{1}\\
	a_{21} &  a_{22} & a_{23} & \cdots & a_{2n} & b_{2}\\
	a_{31} &  a_{32} & a_{33} & \cdots & a_{3n} & b_{3}\\
	\vdots &  \vdots  & \vdots  & \vdots & \vdots  & \vdots\\
	a_{n1} &  a_{n2} & a_{n3} & \cdots & a_{nn} & b_{n}\\
	\end{array} \right] 
\end{equation*}


El cual se basa en las operaciones:


1. Multiplicar la ecuación $i$ - ésima por una constante $\lambda$ y reemplazarla por la original, es decir, $\lambda E_{i}\to E_{i}$.



2. Adicionar el múltiplo de la ecuación $j$ - ésima a la ecuación $i$ - ésima y reemplazarla por la original, es decir, $E_{j}+\lambda E_{i}\to E_{j}$.



3. Intercambiar el orden de las ecuaciones, es decir, $E_{i}\iff E_{j} $.


Ahora en vez de tomar el pivote común, aplicaremos la técnica de **pivote parcial**, la cual se encuentra dada por:


\begin{equation}
	\left| a_{pk}^{(k)} \right| = \max_{k \leq i \leq n} \left| a_{ik}^{(k)} \right|,
\end{equation}

In [3]:
# Importamos la libreria de numpy para manipular arreglos y álgebra lineal
from numpy import array, zeros
import numpy as np

# Importamos la función señalada del determinante
from numpy.linalg import det, solve

In [6]:
# Definimos la matriz con la que estaremos trabajando
# A = array([[1, 2, -1, 3, -8], [2, 0, 2, -1, 13], [-1, 1, 1, -1, 8], [3, 3, -1, 2, -1]], dtype = float)
# B = array([[1, 2, -1, 3, -8], [2, 0, 2, -1, 13], [-1, 1, 1, -1, 8], [3, 3, -1, 2, -1]], dtype = float)
A = array([[0.00300000, 59.14000000, 59.17000000], [5.29100000, -6.13000000, 46.78000000]])
B = array([[0.00300000, 59.14000000, 59.17000000], [5.29100000, -6.13000000, 46.78000000]])

In [7]:
# Validamos que la matriz es invertible

# Calculamos el tamaño del sistema
n = len(A)

if (det(A[:,:n]) != 0 and abs(det(A[:,:n])) > 10 ** (-5)):

    # Imprimimos la matriz aumentada
    print('La matriz aumentada con la que trabajaremos es: \n', A, '\n')

    # Ahora identificamos como se debe proceder para reducir la matriz para la siguiente fila

    # Tomamos la fila para pivote de eliminación hacía abajo
    for j in range(n):
        
        # Pivote inicial
        pivote = j
        
        # Determinamos el elemento de pivote
        for k in range(j+1, n):
            
            # Determinamos si es mayor al elemento
            if A[k,j] > A[pivote, j] :
                
                # Actualizamos el pivote
                pivote = k
                
            # Auxiliar para el cambio
            cambio = A[j, :].copy()

            # Cambiamos lineas
            A[j, :] = A[pivote, :].copy()
            A[pivote, :] = cambio.copy()
        
        # Eliminamos las bajo la fila pivote
        for i in range(j+1, n):
            
            # Determinamos el coeficiente a aplicar en cada fila
            coef = A[i,j] / A[j,j]

            # Realizamos la eliminación
            A[i,:] = A[i,:] - coef * A[j,:]
                
    # Imprimimos la matriz resultado del sistema de ecuaciones
    print('La matriz resultado del proceso de eliminación es: \n', A, '\n')
    
    # Iniciamos el proceso de sustitución hacía atrás
    
    # Creamos una lista para los coeficientes
    x = zeros(n)

    # Primero determinamos el último coeficiente
    x[n-1] = A[n-1, n] / A[n-1, n-1]
    
    # Para los coeficientes restantes debemos aplicar el proceso de sustitución hacía atrás
    for i in range(n-1,-1,-1):

        # Tomamos el valor del vector columna de la matriz aumentada
        b = A[i, n]

        # Comenzamos el proceso de sustitucion hacia atras
        for j in range(i+1, n):
            b = b - A[i,j] * x[j]

        # Realizamos el cociente
        x[i] = b / A[i,i]
    
    # Imprimimos el vector solución
    print('El vector solución es: \n', x)
    
else:
    
    print('La matriz no tiene solución única')

La matriz aumentada con la que trabajaremos es: 
 [[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]] 

La matriz resultado del proceso de eliminación es: 
 [[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]] 

El vector solución es: 
 [10.  1.]


In [8]:
# Validemos el valor con el método directo de python
solve(B[:,:n], B[:,n]) # Ax = b

array([10.,  1.])