# Método iterativo de Jacobi

El método de Jacobi se obtiene a partir de resolver la $i$ - ésima ecuación del sistema de ecuaciones $A\mathbf{x} = \mathbf{b}$ para la variable $x_{i}$, lo que resulta en (siempre y cuando $a_{ii}\neq 0$).


\begin{equation}
	\forall i=1,2,\dots,n\;\;\;\;x_{i}=\sum_{j=1;j\neq i}^{n}\left(-\frac{a_{ij}x_{j}}{a_{ii}}\right)+\frac{b_{i}}{a_{ii}}
\end{equation}


Posteriormente, para cada $k\geq 1$, se generan la siguientes componentes de $x_{i}^{(k)}$ del vector $\mathbf{x}^{(k)}$ a partir de los componentes de $\mathbf{x}^{(k-1)}$, siguiendo la siguiente fórmula:


\begin{equation}
    \forall i=1,2,\dots,n\;\;\;\;x_{i}^{(k)}=\frac{1}{a_{ii}}\sum_{j=1;j\neq i}^{n}\left(-a_{ij}x_{j}^{(k-1)}\right)+b_{i}
\end{equation}


El cual se puede ver en su forma matricial como:


\begin{equation}
    \mathbf{x}^{(k)}=A\mathbf{x}^{(k-1)}+\mathbf{b}
\end{equation}

In [1]:
# Importamos la libreria de numpy para manipular arreglos y álgebra lineal
from numpy import array, zeros, eye
import numpy as np

# Importamos la función señalada del determinante
from numpy.linalg import det, solve, inv

In [2]:
# Definimos los arreglos con los cuales trabajaremos
A = array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]], dtype = float)
b = array([6, 25, -11, 15], dtype = float)

In [3]:
# Definimos la aproximación inicial
x = array([0, 0, 0, 0], dtype = float)

# Tolerancia de la aproximación
tol = 10 ** (-6)

# Maximas iteraciones
maxItera = 100

# Contador
k = 0

In [4]:
# Definimos la operación de la estandarización
def normal(A, b):
    
    # Determinamos la longitud de la matriz
    n = len(A)
    
    # Copia del arreglo
    Aestandar = A.copy()
    
    # Procedemos a normalizar la matriz
    for i in range(n):
        
        # Normalizamos el vector b
        b[i] = b[i] / A[i,i]
        
        # Normalizamos
        Aestandar[i] = Aestandar[i] / A[i,i]
        
        # Eliminamos el elemento de la diagonal
        Aestandar[i,i] = 0
        
    return -Aestandar, b

# Definimos el método de jacobi
def jacobi(A, b, x):
    
    # Calculamos el método
    jacobi = A@x + b
    
    return jacobi

# Definimos el proceso iterativo
def iterajacobi(A, b, x, tol, maxItera):
    
    # Inicializamos el error
    error = 100
    
    # Inicializamos el contador
    k = 0
    
    # iteramos el proceso
    while (error > tol and k < maxItera):
        
        # Actualizamos el contador
        k += 1
        
        # Actualizamos la aproximación
        x1 = jacobi(A, b, x)
        
        # Calculamos el error
        error = max(abs(x - x1))
        
        # Actualizamos
        x = x1
        
        # Imprimimos resultados
        print('Resultados de la iteracion: ', k)
        print('La aproximación de la solución se encuentra dada por:\n {}'.format(x))
        print('El error entre aproximaciones es de {}'.format(error))

In [5]:
A, b = normal(A, b)

In [6]:
iterajacobi(A, b, x, tol, maxItera)

Resultados de la iteracion:  1
La aproximación de la solución se encuentra dada por:
 [ 0.6         2.27272727 -1.1         1.875     ]
El error entre aproximaciones es de 2.272727272727273
Resultados de la iteracion:  2
La aproximación de la solución se encuentra dada por:
 [ 1.04727273  1.71590909 -0.80522727  0.88522727]
El error entre aproximaciones es de 0.9897727272727272
Resultados de la iteracion:  3
La aproximación de la solución se encuentra dada por:
 [ 0.93263636  2.05330579 -1.04934091  1.13088068]
El error entre aproximaciones es de 0.33739669421487584
Resultados de la iteracion:  4
La aproximación de la solución se encuentra dada por:
 [ 1.01519876  1.95369576 -0.96810863  0.97384272]
El error entre aproximaciones es de 0.15703796487603305
Resultados de la iteracion:  5
La aproximación de la solución se encuentra dada por:
 [ 0.9889913   2.01141473 -1.0102859   1.02135051]
El error entre aproximaciones es de 0.05771896130728793
Resultados de la iteracion:  6
La aproximac